name: context-handling-worker

services:
  worker:
    build:
      context: .
      dockerfile: ./Dockerfile.worker
    image: v1-context-handling-worker:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - context_handling_network
    environment:
      LOGGING_LEVEL: INFO
    deploy:
      replicas: ${WORKER_REPLICAS:-10}  # 10 worker processes để xử lý song song (mặc định 10)

networks:
  context_handling_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.7.0.0/24
          gateway: 10.7.0.1
